In [1]:
#import numpy library.
import numpy as np
lst1 = [1,2,3,4,5,6,7,8]
print(lst1)

[1, 2, 3, 4, 5, 6, 7, 8]


In [5]:
#one dimensional Array.
arr1= np.array(lst1)
print(arr1)
print(type(arr1))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [6]:
#two Dimensional Array.
lst2 = [1,2,3,4]
lst3 = [5,6,7,8]
arr2 = np.array([lst2,lst3])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
#3 dimensional Array.
lst4 = [9,10,11,12]
arr3 = np.array([lst2,lst3,lst4])
print(arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
#Reshape a 1-D array of size 6 into 2x3 matrix.
arr4 = arr1.reshape(2,4)
print(arr4)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
print("shape =",arr4.shape)
print("size = ",arr4.size)
print("dtype = ",arr4.dtype)
print("Dimension =",arr4.ndim)

shape = (2, 4)
size =  8
dtype =  int64
Dimension = 2


In [16]:
#zeros Array
arr5 = np.zeros(5)
print(arr5)
print(arr5.dtype)

[0. 0. 0. 0. 0.]
float64


In [19]:
#ones Array.
arr6 = np.ones((4,4))
print(arr6)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
#full Array.
full_array = np.full((3,4),8)
print(full_array)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [22]:
#identity Array.
id_array = np.eye(4)
print(id_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
#empty Array.
print(np.empty(3))

[1. 1. 1.]


In [25]:
print(np.empty(2))

[5.43230922e-312 7.29112202e-304]


In [28]:
print(np.empty(4))

[1. 1. 1. 1.]


In [31]:
#Evenly spaced Array
print(np.arange(2,20,2))

[ 2  4  6  8 10 12 14 16 18]


In [32]:
#specific number of equally(spaced) valuesbetween the range.
print(np.linspace(1,20,5))

[ 1.    5.75 10.5  15.25 20.  ]


In [34]:
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


In [35]:
print(np.linspace(1,10,3))

[ 1.   5.5 10. ]


In [36]:
#random values Array.float
ran_array = np.random.rand(3,2)
print(ran_array)

[[0.32464393 0.53951202]
 [0.76228933 0.79135214]
 [0.04175526 0.58245537]]


In [38]:
#random values Array integer.
ran_intarr = np.random.randint(1,50,(3,3))
print(ran_intarr)

[[24 47 38]
 [40 34 32]
 [26 32 16]]


In [39]:
ran_intarr = np.random.randint(1,50,(3,3))
print(ran_intarr)

[[47 27 38]
 [11  7  5]
 [48 29  2]]
