#  Numpy 

stands for numerical python it is used for numerical and scientific computation.
-----fast numerical computations.
   -- Working with arrays and matrices.
---  Numpy is also used in linear algebra,statitics and random number  capabilities./
    command to install numpy:-
        pip install numpy
        import numpy in code:-
        import numpy as np
    

# Numpy Arrays (core concept):-

# Create an array:-

In [1]:


import numpy as np
a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


# #2D Array:(matrix):

In [2]:

b = np.array([[1,2,3],[4,5,6]])
print(b)


[[1 2 3]
 [4 5 6]]


# Array properties:




In [3]:
print(a.ndim)# number of dimenssions.

1


In [4]:

print(b.ndim)

2


In [5]:
print(a.shape)#shape (no.of rows and no.of coloumns).

(4,)


In [6]:
print(a.size)#total no.of elements in array.

4


In [7]:
print(b.size)

6


In [8]:
print(a.dtype)#data type.

int64


In [9]:
print(b.shape)


(2, 3)


# common Array Creation functions:


In [10]:
arr = np.zeros((2,3))   # This function creates a matrix 2x3 of all zeros.
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
arr1 = np.ones((2,3))   # this function creates a matriz 2x3 of all ones.
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
arr2=np.eye(3)        # this function creates a identity matrix of 3x3 .
print(arr2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
arr3=np.arange(1,10,2)  #this function generates numbers in given range.
print(arr3)

[1 3 5 7 9]


In [14]:
arr4=np.linspace(1,5,5) #this function generates evenly spaced numbers.
print(arr4)    

[1. 2. 3. 4. 5.]


In [15]:
arr5=np.random.rand(3,3) # this function generates random numbers
print(arr5)

[[0.64790191 0.22742603 0.43972155]
 [0.32773226 0.58645701 0.80027131]
 [0.62307479 0.98128447 0.73622163]]


# Indexing and Slicing:

In [16]:
arr = np.array([10,20,30,40,50])
print(arr) # [10 20 30 40 50]



[10 20 30 40 50]


In [17]:
print(arr[0]) # 10

10


In [18]:
print(arr[1:4]) # [20,30,40]

[20 30 40]


In [19]:
mat = np.array([[1,2,3],[4,5,6]])
print(mat[1,1]) #5

5


In [20]:

print(mat[:,1]) # all rows , column 1

[2 5]


# Array Operations.

In [21]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


In [22]:
print(a*b)

[ 4 10 18]


In [23]:
print(a**2)

[1 4 9]


# mathematical functions:-

In [24]:
print(np.max(a))# display maximum elements of array a ---- 3
print(np.min(a))# display minimum elements os array a--- 1
print(np.mean(a))#display average of all elements of array a---2.0
print(np.sum(a))# display sum of all elements of array array a ---6
print(np.std(a))# display standard deviation.0.816496

3
1
2.0
6
0.816496580927726


# Linear Algebra Operations:


In [25]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(np.dot(A,B))# matrix multiplication

[[19 22]
 [43 50]]


In [26]:
print(np.linalg.det(A))# Determinant


-2.0000000000000004


In [27]:
print(np.linalg.inv(A))# Inverse

[[-2.   1. ]
 [ 1.5 -0.5]]


In [28]:
print(np.__version__)


2.4.0
